/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppApplicationsIndexRouteImport } from './routes/_app/applications/index'
import { Route as AppCvsIndexRouteImport } from './routes/_app/cvs/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppDashboardJobIdRouteImport } from './routes/_app/dashboard/$jobId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppTailoringSessionIdRouteImport } from './routes/_app/tailoring/$sessionId'
import { Route as AppTailoringPrepRouteImport } from './routes/_app/tailoring/prep'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const AppCvsIndexRoute = AppCvsIndexRouteImport.update({
  id: '/cvs/',
  path: '/cvs/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardJobIdRoute = AppDashboardJobIdRouteImport.update({
  id: '/dashboard/$jobId',
  path: '/dashboard/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppTailoringSessionIdRoute = AppTailoringSessionIdRouteImport.update({
  id: '/tailoring/$sessionId',
  path: '/tailoring/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppTailoringPrepRoute = AppTailoringPrepRouteImport.update({
  id: '/tailoring/prep',
  path: '/tailoring/prep',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/$jobId': typeof AppDashboardJobIdRoute
  '/tailoring/$sessionId': typeof AppTailoringSessionIdRoute
  '/tailoring/prep': typeof AppTailoringPrepRoute
  '/applications/': typeof AppApplicationsIndexRoute
  '/cvs/': typeof AppCvsIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/$jobId': typeof AppDashboardJobIdRoute
  '/tailoring/$sessionId': typeof AppTailoringSessionIdRoute
  '/tailoring/prep': typeof AppTailoringPrepRoute
  '/applications': typeof AppApplicationsIndexRoute
  '/cvs': typeof AppCvsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard/$jobId': typeof AppDashboardJobIdRoute
  '/_app/tailoring/$sessionId': typeof AppTailoringSessionIdRoute
  '/_app/tailoring/prep': typeof AppTailoringPrepRoute
  '/_app/applications/': typeof AppApplicationsIndexRoute
  '/_app/cvs/': typeof AppCvsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/$jobId'
    | '/tailoring/$sessionId'
    | '/tailoring/prep'
    | '/applications/'
    | '/cvs/'
    | '/dashboard/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/$jobId'
    | '/tailoring/$sessionId'
    | '/tailoring/prep'
    | '/applications'
    | '/cvs'
    | '/dashboard'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/dashboard/$jobId'
    | '/_app/tailoring/$sessionId'
    | '/_app/tailoring/prep'
    | '/_app/applications/'
    | '/_app/cvs/'
    | '/_app/dashboard/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/applications/': {
      id: '/_app/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cvs/': {
      id: '/_app/cvs/'
      path: '/cvs'
      fullPath: '/cvs/'
      preLoaderRoute: typeof AppCvsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/$jobId': {
      id: '/_app/dashboard/$jobId'
      path: '/dashboard/$jobId'
      fullPath: '/dashboard/$jobId'
      preLoaderRoute: typeof AppDashboardJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tailoring/$sessionId': {
      id: '/_app/tailoring/$sessionId'
      path: '/tailoring/$sessionId'
      fullPath: '/tailoring/$sessionId'
      preLoaderRoute: typeof AppTailoringSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tailoring/prep': {
      id: '/_app/tailoring/prep'
      path: '/tailoring/prep'
      fullPath: '/tailoring/prep'
      preLoaderRoute: typeof AppTailoringPrepRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardJobIdRoute: typeof AppDashboardJobIdRoute
  AppTailoringSessionIdRoute: typeof AppTailoringSessionIdRoute
  AppTailoringPrepRoute: typeof AppTailoringPrepRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppCvsIndexRoute: typeof AppCvsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardJobIdRoute: AppDashboardJobIdRoute,
  AppTailoringSessionIdRoute: AppTailoringSessionIdRoute,
  AppTailoringPrepRoute: AppTailoringPrepRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppCvsIndexRoute: AppCvsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
